/*
 Copyright 2013 Blue State Digital, Inc.
 Blue State Digital Google Analytics Integration Library

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var _gaq=_gaq||[],optimizely=optimizely||[];_gaq.push(["_setSiteSpeedSampleRate",10],["_setAllowAnchor",!0],["_setAllowLinker",!0]);
(function(b){function p(c){var a=document.createElement("a");a.href=c;return a}function q(c){return c.charAt(0).toUpperCase()+c.slice(1).toLowerCase()}function m(c){return c&&p(c).pathname.replace(/(^\/?)/,"/")}function e(c){return(RegExp("(?:^|; )"+c+"=([^;]*)").exec(document.cookie)||[]).pop()}function f(c,a,b){ga_integration_config.nocookie||(b=b?"; expires="+(new Date(864E5*b+(new Date).getTime())).toGMTString():"",document.cookie=c+"="+a+b+"; path=/; domain="+ga_integration_config.cookiedomain)}
function n(c,a,b,d,l){_gaq.push(["_trackEvent",c,a,d,l],["_trackSocial",c,a,b,d])}function r(c){var a=1,b=0,d;if(c)for(a=0,d=c.length-1;0<=d;d--)b=c.charCodeAt(d),a=(a<<6&268435455)+b+(b<<14),b=a&266338304,a=0!=b?a^b>>21:a;return a}function s(c){return c.match(/contribution/i)&&b("form#contribution").length?(c=Math.round(b("#amt_other:checked").length?b('input[name="amount_other"]').val():b('input[name="amount"]:checked').val()),c!=c||1E9<Math.abs(c)?0:c):0}function t(c){ga_integration_config.data.action=
c;var a=c.modulename;if(a){f("_bsda_s",1,180);var g=c.formname,d=c.transaction_amt;if(c.savedPaymentInfo)a="Quick Donate Opt-In",f("_bsda_q",1,180);else if(d){f("_bsda_c",Math.round(d),180);var l=c.contribution_key,h=-1!==b.inArray(d,c.pageamounts)?Math.round(d):"other",h=c.contribution_page_id+"_"+h,u=+c.pagetype,e=+c.is_recurring?"BSD Recurring":"BSD";c.used_quick_donate&&(e+=" Quick Donate",h+="_QD",f("_bsda_q",1,180));_gaq.push(["_addTrans",l,"",d,"0","0","","",""],["_addItem",l,h,g,e+(4===u?
" Memberships":2===u?" Tickets":3===u?" Custom Contributions":" Contributions"),d,"1"],["_trackTrans"]);optimizely.push(["trackEvent","bsdtracker",100*d])}_gaq.push(["_trackEvent","Completions",a,g,Math.ceil(d||0)]);optimizely.push(["trackEvent","bsdtracker_"+a])}}window.ga_integration_config=window.ga_integration_config||{};if(!ga_integration_config.cookiedomain){var v=location.hostname.match(/\.uk$/)?-3:-2;ga_integration_config.cookiedomain=location.hostname.split(".").slice(v).join(".")}var w=
window.onerror;window.onerror=function(b,a,g){w&&w.apply(this,arguments);_gaq.push(["_trackEvent","JavaScript Errors",b,a+"_"+g,0,!0])};var k=function(){var b={};location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(a,g,d){b[g]=d});return b}();k.source&&_gaq.push(["_setCustomVar",1,"Source",k.source,2]);k.subsource&&_gaq.push(["_setCustomVar",5,"Subsource",k.subsource,2]);e("msid")&&(v=ga_integration_config.msid_seed?""+(parseInt(e("msid"),16)^ga_integration_config.msid_seed):e("msid"),_gaq.push(["_setCustomVar",
2,"msid",v,2]));_gaq.push(["_setCustomVar",3,"Has GUID",""+!!e("guid"),2]);_gaq.push(["_setCustomVar",4,"Has Spud",""+!!e("spud"),2]);if(!b||!b.fn)throw Error("No jQuery found.");b.fn.analytics=function(c,a,g){if(!c)return this.trigger(a||"mousedown");var d=a?a+".analytics":"keydown.analytics mousedown.analytics",l=g||"one",h=function(d){if(a||"mousedown"===d.type||13===d.which)"function"===typeof c?c.apply(this):b.isArray(c)&&c[1]&&"number"!==typeof c[1]?_gaq.push(["_trackEvent"].concat(c)):("string"===
typeof c||b.isArray(c))&&optimizely.push(["trackEvent"].concat(c))};return g&&!b.fn.live?b(document).delegate(this.selector,d,h):this[l](d,h)};b.fn.registerBSDError=function(b){this.length&&_gaq.push(["_trackEvent","Error",b,m(document.referrer),s(b),!0])};r(location.hostname)%7!==(new Date).getDay()||1!==Math.ceil(100*Math.random())||e("__bsdzh")||((new Image).src="//bsd-analytics.appspot.com/?"+b.param({hostname:location.hostname,src:b("script:last").attr("src"),jQ:b.fn.jquery}));ga_integration_config.util=
{createCookie:f,readCookie:e,getURLParam:k,hash:r,contrib_amt:s,bsdtracker_to_ga:t,getPathname:m,social_event:n,proper:q};ga_integration_config.data={};b(document).ready(function(){function c(a){if("mousedown"===a.type||13===a.which)$this=b(this),$this.unbind("keydown mousedown",c),a=$this.is("form")?$this:$this.closest("form"),a=a.attr("id")||a.attr("name")||a.attr("action")||"(none)",_gaq.push(["_trackEvent","Form Submits",a,location.pathname,s(a)])}b("input").filter('[type="image"],[type="submit"]').bind("mousedown",
c);b("form").bind("keydown",c);b("span.signuperror").registerBSDError("Signup");b("div.contriberrorbanner").registerBSDError("Contribution");b("#invitationpage .error").registerBSDError("Share");b("[href^='http'], [href^='//']").analytics(function(a){if(this.hostname!==location.hostname)if(a=/(facebook|twitter|addthis|youtube|pinterest)(\.com)/i.exec(this.href)){var b=this.href.match(/facebook\.com\/sharer.php/)?decodeURIComponent(this.href.replace("http://www.facebook.com/sharer.php?u=","")):this.href;
n(q(a[1]),"click",b,m(b))}else _gaq.push(["_trackEvent","Exits",p(this.href).hostname,this.href])},null,"live");b('a[href$=".pdf"]').analytics(function(a){_gaq.push(["_trackEvent","PDF Clicks",b(this).text(),this.href,0,!0])});b("video,audio").bind("play ended pause",function(a){_gaq.push(["_trackEvent",q(this.nodeName),q(a.type),this.src,0,!0])});b.fn._link=b.fn._link||function(a,c){var d=c||location.hostname.split(".").slice(-2).join(".");this.one("click",function(c){~b.inArray(d,a)&&d!=this.hostname.split(".").slice(-2).join(".")&&
($this=b(this),_gaq.push(function(){$this.attr("href",function(a,b){return _gat._getTrackerByName()._getLinkerUrl(b,!0)})}))})};window.BSDTracker?t(BSDTracker[BSDTracker.signup?"signup":BSDTracker.contribution?"contribution":""].jsonData):k.td&&b.getJSON((ga_integration_config.bsddomain?ga_integration_config.bsddomain:"//www.bluestatedigital.com")+"/page/tracking/action-decode?td="+k.td+"&callback=?",function(a){t(a)});window.bQuery&&bQuery.fn.mailcheck&&b("#email").blur(function(){var a=b(".bsd-mailcheck");
if(a.length){var c=a.text();_gaq.push(["_trackEvent","Mailcheck","Shown",c,0,!0]);a=function(){_gaq.push(["_trackEvent","Mailcheck","Clicked",c,0,!0])};b.fn.live?b(".bsd-mailcheck a").live("click",a):b("#signup").delegate(".bsd-mailcheck a","click",a)}});b(window).load(function(){optimizely.variationNamesMap&&b.each(optimizely.variationNamesMap,function(a,b){_gaq.push(["_trackEvent","Optimizely",optimizely.allExperiments[a].name,b,0,!0])});!1!==ga_integration_config.nocookie&&!1!==ga_integration_config.nospud&&
!1!==ga_integration_config.noloe&&e("guid")&&!e("loega")&&(ga_integration_config.bsddomain||location.pathname.match(/^\/page\//))&&b.getJSON((ga_integration_config.bsddomain||"")+"/page/graph/loe/"+e("guid")+"?callback=?",function(a){var b=[],c="",l=0;ga_integration_config.data.loe=a;for(var h in a)a[h]&&"boolean"===typeof a[h]&&b.push(h);b=b.length?b.sort().join("-"):"Anonymous";a.donor&&(l=Math.ceil(a.highest_previous_contribution),c=""+l,f("_bsda_c",l,180));a.email&&f("_bsda_s",1,180);a.qd_enrolled&&
f("_bsda_q",1,180);_gaq.push(["_trackEvent","Ladder of Engagement",b,c,l,!0]);f("loega",1)});(function(){if(!0!==ga_integration_config.nospud&&!0!==ga_integration_config.nocookie){var a=e("__utmz")||"";if(!e("spud")&&!k.source&&!e("source")||a&&r(a).toString()!==e("__bsdzh")){var c=(ga_integration_config.bsddomain?ga_integration_config.bsddomain:"")+"/page/spud?jsonp=?",d=function(){var c,d;d=a.split(".").slice(4).join(".").split("|");var e={};b.each(d,function(a,b){var c=b.split("=");c[1]&&!c[1].match(/^\(.*\)$/)&&
(e[c[0]]=decodeURIComponent(c[1]))});if(e.utmgclid)c="cpc_google",d=e.utmctr;else{var g=[];b.each(e,function(a,b){"utmcmd"!==a&&"utmcsr"!==a&&"utmcct"!==a&&g.push(b)});e.utmcmd&&e.utmcsr&&(c=e.utmcmd+"_"+e.utmcsr);d=g.sort().join("_")}(k.source||c)&&f("source",k.source||c,7);(k.subsource||d)&&f("subsource",k.subsource||d,7)};f("__bsdzh",r(a));e("spud")?b.ajax({url:c,dataType:"jsonp",data:{type:"getm",field:"source,subsource"},jsonp:"jsonp",success:function(a){a.source||a.subsource||d()}}):d()}}})();
window.FB&&FB.Event&&(FB.Event.subscribe("edge.create",function(a){n("Facebook","Like",a,m(a),1)}),FB.Event.subscribe("edge.remove",function(a){n("Facebook","Unlike",a,m(a),-1)}),FB.Event.subscribe("comment.create",function(a){n("Facebook","Comment",a.href,m(a.href),1)}),FB.Event.subscribe("comment.remove",function(a){n("Facebook","Uncomment",a.href,m(a.href),-1)}));b("[href*='.facebook.com/sharer.php?']").bind("mousedown",function(){n("Facebook","Share",b(this).attr("href"),m(b(this).attr("href")),
1)});window.twttr&&twttr.events&&twttr.ready&&twttr.ready(function(a){"click tweet retweet follow favorite".replace(/\w+/g,function(c){a.events.bind(c,function(a){var c;a&&a.target&&(a.target.src?c=p(decodeURIComponent((a.target.src.match(/[&#?](url=)([^&]*)/)||[""]).pop())):a&&a.target&&a.target.href&&b.each(decodeURIComponent(a.target.search).replace(/\+/g," ").split(/&| |\=/g),function(a,b){if(b.match(/(^https?:\/\/)|(^www.)/))return c=p(b),!1}));c&&n("Twitter",a.type,c.href.replace(c.hash,""),
c.pathname)})})})})})})(window.jQuery||window.bQuery);