/*
 Copyright 2013 Blue State Digital, Inc.
 Blue State Digital Google Analytics Integration Library

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var _gaq=_gaq||[],optimizely=optimizely||[];_gaq.push(["_setSiteSpeedSampleRate",10],["_setAllowAnchor",!0],["_setAllowLinker",!0]);
(function(b){function m(c){var a=document.createElement("a");a.href=c;return a}function n(c){return c.charAt(0).toUpperCase()+c.slice(1).toLowerCase()}function k(c){return c&&m(c).pathname.replace(/(^\/?)/,"/")}function e(c){return(RegExp("(?:^|; )"+c+"=([^;]*)").exec(document.cookie)||[]).pop()}function f(c,a,b){ga_integration_config.nocookie||(b=b?"; expires="+(new Date(864E5*b+(new Date).getTime())).toGMTString():"",document.cookie=c+"="+a+b+"; path=/; domain="+ga_integration_config.cookiedomain)}
function l(c,a,b,d,i){_gaq.push(["_trackEvent",c,a,d,i],["_trackSocial",c,a,b,d])}function o(c){var a=1,b=0,d;if(c){a=0;for(d=c.length-1;0<=d;d--)b=c.charCodeAt(d),a=(a<<6&268435455)+b+(b<<14),b=a&266338304,a=0!=b?a^b>>21:a}return a}function p(c){return c.match(/contribution/i)&&b("form#contribution").length?(c=Math.round(!b("#amt_other:checked").length?b('input[name="amount"]:checked').val():b('input[name="amount_other"]').val()),c!=c||1E9<Math.abs(c)?0:c):0}function q(c){ga_integration_config.data.action=
c;var a=c.modulename;if(a){f("_bsda_s",1,180);var j=c.formname,d=c.transaction_amt;if(c.savedPaymentInfo)a="Quick Donate Opt-In",f("_bsda_q",1,180);else if(d){f("_bsda_c",Math.round(d),180);var i=c.contribution_key,g=-1!==b.inArray(d,c.pageamounts)?Math.round(d):"other",g=c.contribution_page_id+"_"+g,r=+c.pagetype,e=+c.is_recurring?"BSD Recurring":"BSD";c.used_quick_donate&&(e+=" Quick Donate",g+="_QD",f("_bsda_q",1,180));_gaq.push(["_addTrans",i,"",d,"0","0","","",""],["_addItem",i,g,j,e+(4===r?
" Memberships":2===r?" Tickets":3===r?" Custom Contributions":" Contributions"),d,"1"],["_trackTrans"]);optimizely.push(["trackEvent","bsdtracker",100*d])}_gaq.push(["_trackEvent","Completions",a,j,Math.ceil(d||0)]);optimizely.push(["trackEvent","bsdtracker_"+a])}}window.ga_integration_config=window.ga_integration_config||{};if(!ga_integration_config.cookiedomain){var s=location.hostname.match(/\.uk$/)?-3:-2;ga_integration_config.cookiedomain=location.hostname.split(".").slice(s).join(".")}var t=
window.onerror;window.onerror=function(c,a,b){t&&t.apply(this,arguments);_gaq.push(["_trackEvent","JavaScript Errors",c,a+"_"+b,0,!0])};var h=function(){var b={};location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(a,j,d){b[j]=d});return b}();h.source&&_gaq.push(["_setCustomVar",1,"Source",h.source,2]);h.subsource&&_gaq.push(["_setCustomVar",5,"Subsource",h.subsource,2]);e("msid")&&(s=ga_integration_config.msid_seed?""+(parseInt(e("msid"),16)^ga_integration_config.msid_seed):e("msid"),_gaq.push(["_setCustomVar",
2,"msid",s,2]));_gaq.push(["_setCustomVar",3,"Has GUID",""+!!e("guid"),2]);_gaq.push(["_setCustomVar",4,"Has Spud",""+!!e("spud"),2]);if(!b||!b.fn)throw Error("No jQuery found.");b.fn.analytics=function(c,a,j){if(!c)return this.trigger(a||"mousedown");var d=a?a+".analytics":"keydown.analytics mousedown.analytics",i=j||"one",g=function(d){if(a||d.type==="mousedown"||d.which===13)typeof c==="function"?c.apply(this):b.isArray(c)&&c[1]&&typeof c[1]!=="number"?_gaq.push(["_trackEvent"].concat(c)):(typeof c===
"string"||b.isArray(c))&&optimizely.push(["trackEvent"].concat(c))};return j&&!b.fn.live?b(document).delegate(this.selector,d,g):this[i](d,g)};b.fn.registerBSDError=function(b){this.length&&_gaq.push(["_trackEvent","Error",b,k(document.referrer),p(b),true])};o(location.hostname)%7===(new Date).getDay()&&1===Math.ceil(100*Math.random())&&!e("__bsdzh")&&((new Image).src="//bsd-analytics.appspot.com/?"+b.param({hostname:location.hostname,src:b("script:last").attr("src"),jQ:b.fn.jquery}));ga_integration_config.util=
{createCookie:f,readCookie:e,getURLParam:h,hash:o,contrib_amt:p,bsdtracker_to_ga:q,getPathname:k,social_event:l,proper:n};ga_integration_config.data={};b(document).ready(function(){function c(a){if(a.type==="mousedown"||a.which===13){$this=b(this);$this.unbind("keydown mousedown",c);a=$this.is("form")?$this:$this.closest("form");a=a.attr("id")||a.attr("name")||a.attr("action")||"(none)";_gaq.push(["_trackEvent","Form Submits",a,location.pathname,p(a)])}}b("input").filter('[type="image"],[type="submit"]').bind("mousedown",
c);b("form").bind("keydown",c);b("span.signuperror").registerBSDError("Signup");b("div.contriberrorbanner").registerBSDError("Contribution");b("#invitationpage .error").registerBSDError("Share");b("[href^='http'], [href^='//']").analytics(function(){if(this.hostname!==location.hostname){var a=/(facebook|twitter|addthis|youtube|pinterest)(\.com)/i.exec(this.href);if(a){var b=this.href.match(/facebook\.com\/sharer.php/)?decodeURIComponent(this.href.replace("http://www.facebook.com/sharer.php?u=","")):
this.href;l(n(a[1]),"click",b,k(b))}else _gaq.push(["_trackEvent","Exits",m(this.href).hostname,this.href])}},null,"live");b('a[href$=".pdf"]').analytics(function(){_gaq.push(["_trackEvent","PDF Clicks",b(this).text(),this.href,0,true])});b("video,audio").bind("play ended pause",function(a){_gaq.push(["_trackEvent",n(this.nodeName),n(a.type),this.src,0,true])});b.fn._link=b.fn._link||function(a,c){var d=c||location.hostname.split(".").slice(-2).join(".");this.one("click",function(){if(~b.inArray(d,
a)&&d!=this.hostname.split(".").slice(-2).join(".")){$this=b(this);_gaq.push(function(){$this.attr("href",function(a,b){return _gat._getTrackerByName()._getLinkerUrl(b,true)})})}})};window.BSDTracker?q(BSDTracker[BSDTracker.signup?"signup":BSDTracker.contribution?"contribution":""].jsonData):h.td&&b.getJSON((ga_integration_config.bsddomain?ga_integration_config.bsddomain:"//www.bluestatedigital.com")+"/page/tracking/action-decode?td="+h.td+"&callback=?",function(a){q(a)});window.bQuery&&bQuery.fn.mailcheck&&
b("#email").blur(function(){var a=b(".bsd-mailcheck");if(a.length){var c=a.text();_gaq.push(["_trackEvent","Mailcheck","Shown",c,0,true]);a=function(){_gaq.push(["_trackEvent","Mailcheck","Clicked",c,0,true])};b.fn.live?b(".bsd-mailcheck a").live("click",a):b("#signup").delegate(".bsd-mailcheck a","click",a)}});b(window).load(function(){optimizely.variationNamesMap&&b.each(optimizely.variationNamesMap,function(a,b){_gaq.push(["_trackEvent","Optimizely",optimizely.allExperiments[a].name,b,0,true])});
if(ga_integration_config.nocookie!==false&&ga_integration_config.nospud!==false&&ga_integration_config.noloe!==false&&e("guid")&&!e("loega")&&(ga_integration_config.bsddomain||location.pathname.match(/^\/page\//)))b.getJSON((ga_integration_config.bsddomain||"")+"/page/graph/loe/"+e("guid")+"?callback=?",function(a){var b=[],c="",i=0;ga_integration_config.data.loe=a;for(var g in a)a[g]&&typeof a[g]==="boolean"&&b.push(g);b=b.length?b.sort().join("-"):"Anonymous";if(a.donor){i=Math.ceil(a.highest_previous_contribution);
c=""+i;f("_bsda_c",i,180)}a.email&&f("_bsda_s",1,180);a.qd_enrolled&&f("_bsda_q",1,180);_gaq.push(["_trackEvent","Ladder of Engagement",b,c,i,true]);f("loega",1)});(function(){if(!(ga_integration_config.nospud===true||ga_integration_config.nocookie===true)){var a=e("__utmz")||"";if(!e("spud")&&!h.source&&!e("source")||a&&o(a).toString()!==e("__bsdzh")){var c=(ga_integration_config.bsddomain?ga_integration_config.bsddomain:"")+"/page/spud?jsonp=?",d=function(){var c,d;d=a.split(".").slice(4).join(".").split("|");
var e={};b.each(d,function(a,b){var c=b.split("=");c[1]&&!c[1].match(/^\(.*\)$/)&&(e[c[0]]=decodeURIComponent(c[1]))});if(e.utmgclid){c="cpc_google";d=e.utmctr}else{var j=[];b.each(e,function(a,b){a!=="utmcmd"&&a!=="utmcsr"&&a!=="utmcct"&&j.push(b)});e.utmcmd&&e.utmcsr&&(c=e.utmcmd+"_"+e.utmcsr);d=j.sort().join("_")}if(h.source||c)f("source",h.source||c,7);if(h.subsource||d)f("subsource",h.subsource||d,7)};f("__bsdzh",o(a));e("spud")?b.ajax({url:c,dataType:"jsonp",data:{type:"getm",field:"source,subsource"},
jsonp:"jsonp",success:function(a){!a.source&&!a.subsource&&d()}}):d()}}})();if(window.FB&&FB.Event){FB.Event.subscribe("edge.create",function(a){l("Facebook","Like",a,k(a),1)});FB.Event.subscribe("edge.remove",function(a){l("Facebook","Unlike",a,k(a),-1)});FB.Event.subscribe("comment.create",function(a){l("Facebook","Comment",a.href,k(a.href),1)});FB.Event.subscribe("comment.remove",function(a){l("Facebook","Uncomment",a.href,k(a.href),-1)})}window.twttr&&twttr.events&&twttr.ready&&twttr.ready(function(a){"click tweet retweet follow favorite".replace(/\w+/g,
function(c){a.events.bind(c,function(a){var c;a&&a.target&&(a.target.src?c=m(decodeURIComponent((a.target.src.match(/[&#?](url=)([^&]*)/)||[""]).pop())):a&&a.target&&a.target.href&&b.each(decodeURIComponent(a.target.search).replace(/\+/g," ").split(/&| |\=/g),function(a,b){if(b.match(/(^https?:\/\/)|(^www.)/)){c=m(b);return false}}));c&&l("Twitter",a.type,c.href.replace(c.hash,""),c.pathname)})})})})})})(window.jQuery||window.bQuery);
